apiVersion: apps/v1
kind: Deployment
metadata:
  name: jade-backend
  namespace: jade-security
  labels:
    app: jade-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jade-backend
  template:
    metadata:
      labels:
        app: jade-backend
    spec:
      containers:
      - name: jade-backend
        image: jade-security:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: jade-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: jade-config
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jade-secrets
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jade-secrets
              key: JWT_SECRET_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: jade-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: jade-secrets
              key: ANTHROPIC_API_KEY
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: jade-secrets
              key: GEMINI_API_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"